const FETCH_DATA = 'FETCH_DATA';
const FILTER_DATA = 'FILTER_DATA';
const UPDATE_DATA = 'UPDATE_DATA';
const FETCH_BY_ID = 'FETCH_BY_ID';

export { FETCH_DATA, FILTER_DATA, UPDATE_DATA, FETCH_BY_ID };